name: security

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    emails:
        name: Check commit emails
        runs-on: ubuntu-latest
        steps:
            -   name: 🔐 Checkout repository 🔐
                uses: actions/checkout@v6

            -   name: 🔐 Check commits 🔐
                run: |
                    insecure_emails_author=$(git log --format="%ae" | grep "@gmail.com" | sort -u | wc -l || true)
                    insecure_emails_committer=$(git log --format="%ce" | grep "@gmail.com" | sort -u | wc -l || true)

                    if [ $insecure_emails_author -ne "0" ]; then
                        echo "found ${insecure_emails_author} insecure author email addresses in git history!"
                        exit 1
                    fi
                    if [ $insecure_emails_committer -ne "0" ]; then
                        echo "found ${insecure_emails_committer} insecure committer email addresses in git history!"
                        exit 1
                    fi
