#!/bin/bash

set -euo pipefail

# --source excludes forked repos
readarray -t organization < \
    <(gh repo list rarestype --source --json nameWithOwner -q '.[].nameWithOwner')
readarray -t additional < Scripts/AdditionalRepositories

for id in "${organization[@]}" "${additional[@]}"; do
    echo "validating repo '${id}'"
    Scripts/Check "$id"
done
