#!/bin/bash

set -euo pipefail

mkdir -p repositories/
cd repositories

repository=${1##*/}

if [ ! -d "$repository" ]; then
    git clone -q "https://github.com/$1"
fi

cd "$repository"

# if there are no emails, grep will also fail, which is why coalescence is needed
insecure_emails_history=$(git log --format="%ae %ce" | grep "@gmail.com" | sort -u | wc -l || true)
insecure_emails_mailmap=$(grep "@gmail.com" .mailmap | sort -u | wc -l || true)

if [ $insecure_emails_history -ne "0" ]; then
    echo "found ${insecure_emails_history} insecure email addresses in git history of repo '${repository}'!"
    exit 1
fi
if [ $insecure_emails_mailmap -ne "0" ]; then
    echo "found ${insecure_emails_mailmap} insecure email addresses in .mailmap of repo '${repository}'!"
    exit 1
fi
