#!/bin/bash

set -euo pipefail

mkdir -p repositories/
cd repositories

repository=${1##*/}

if [ ! -d "$repository" ]; then
    git clone "https://github.com/$1"
fi

cd "$repository"

insecure_emails_author=$(git log --format="%ae" | grep "@gmail.com" | sort -u | wc -l)
insecure_emails_committer=$(git log --format="%ce" | grep "@gmail.com" | sort -u | wc -l)

if [ $insecure_emails_author -ne "0" ]; then
    echo "found ${insecure_emails_author} insecure author email addresses in repo '${repository}'!"
    exit 1
fi
if [ $insecure_emails_committer -ne "0" ]; then
    echo "found ${insecure_emails_committer} insecure committer email addresses in repo '${repository}'!"
    exit 1
fi
