#!/bin/bash

set -euo pipefail

# --source excludes forked repos
readarray -t organization < \
    <(gh repo list rarestype --source --json nameWithOwner -q '.[].nameWithOwner')
readarray -t additional < Scripts/AdditionalRepositories

any_failed=0

for id in "${organization[@]}" "${additional[@]}"; do
    if ! Scripts/Check "$id"; then
        echo "❗ repository $id contains insecure email addresses!!!"
        any_failed=1
    else
        echo "💞 repository $id contains no insecure email addresses!"
    fi
done

if [ "$any_failed" -ne 0 ]; then
    echo "One or more repositories contains insecure emails!"
    echo "please create a mailmap file, then run"
    echo "git filter-repo --mailmap ../../.mailmap"
    echo "git filter-repo --path .mailmap --invert-paths"
    echo "git push origin --force --all"
    echo "git push origin --force --tags"
    exit 1
fi
