#!/bin/bash

set -euo pipefail

tag='autosync'

# --source excludes forked repos
readarray -t organization < \
    <(gh repo list rarestype --source --topic "$tag" --json nameWithOwner -q '.[].nameWithOwner')
readarray -t additional_unfiltered < Scripts/AdditionalRepositories

additional=()
for repo in "${additional_unfiltered[@]}"; do
    # skip empty lines
    if [ -z "$repo" ]; then continue; fi

    if gh api "repos/$repo" --jq '.topics[]' | grep -Fxq "$tag"; then
        additional+=("$repo")
    fi
done

templates=$(realpath Templates)

for id in "${organization[@]}" "${additional[@]}"; do
    # we do not want to push to this repo itself
    if [ "$id" != 'rarestype/rarestcheck' ]; then
        Scripts/Sync "$templates" "$id"
    fi
done
