#!/bin/bash

set -euo pipefail

swift --version

swift package dollup --allow-writing-to-package-directory
git diff --exit-code

swift build -c release --build-tests \
    --explicit-target-dependency-import-check=error

Scripts/TestAgentTooling

if [[ $(uname) == 'Linux' ]]; then
    swift run -c release rarestcheck sync Templates/Repositories -t autosync
fi
