name: audit

on:
    workflow_dispatch:
    # This runs on the 52nd minute of every hour, which is a random number we choose to
    # avoid peak minutes around :00 and :30
    schedule:
        - cron: "52 * * * *"

jobs:
    emails:
        runs-on: ubuntu-latest
        name: Audit email addresses

        steps:
            -   name: 💗 Check email addresses 💗
                run: Scripts/CheckAll
