name: Audit

permissions:
    contents: write
on:
    workflow_dispatch:
    push:
        branches: [ master ]
    # This runs on the 52nd minute of every hour, which is a random number we choose to
    # avoid peak minutes around :00 and :30
    schedule:
        - cron: "52 * * * *"

jobs:
    emails:
        runs-on: ubuntu-24.04-arm
        name: email addresses

        steps:
            -   name: 💞 Checkout repository 💞
                uses: actions/checkout@v6

            -   name: 💞 Install rarestcheck tool 💞
                uses: rarestype/r2-install-action@v1
                with:
                    archive: rarestcheck.tar.gz

            -   name: 💞 Check email addresses 💞
                run: rarestcheck exec Scripts/AdditionalRepositories --script Scripts/Check
                env:
                    AUTOMATION_APP_CLIENT: ${{ vars.AUTOMATION_APP_CLIENT }}
                    AUTOMATION_APP_SECRET: ${{ secrets.AUTOMATION_APP_SECRET }}
                    AUTOMATION_APP_KEY: ${{ secrets.AUTOMATION_APP_KEY }}
                    AUTOMATION_PAT_FALLBACK: ${{ secrets.AUTOMATION_PAT }}

            -   name: 💞 Update badge 💞
                uses: rarestype/rarestbadge@v1
                if: always()
