name: Sync

permissions:
    contents: write
on:
    workflow_dispatch:
    push:
        branches: [ master ]
    # run this once a day
    schedule:
        - cron: "52 6 * * *"
jobs:
    push:
        runs-on: ubuntu-latest
        name: push templates

        steps:
            -   name: 💞 Checkout repository 💞
                uses: actions/checkout@v6

            -   name: 💞 Setup credentials 💞
                run: gh auth setup-git
                env:
                    GH_TOKEN: ${{ secrets.AUTOMATION_PAT }}

            -   name: 💞 Synchronize templates 💞
                run: Scripts/SyncAll --push
                env:
                    GH_TOKEN: ${{ secrets.AUTOMATION_PAT }}

            -   name: 💞 Update badge 💞
                uses: rarestype/rarestbadge@v1
                if: always()
                with:
                    badge: Sync
                    title: sync
