name: Sync

permissions:
    contents: write
on:
    workflow_dispatch:
    # run this once a day
    schedule:
        - cron: "52 6 * * *"
jobs:
    push:
        runs-on: ubuntu-24.04-arm
        name: push templates

        steps:
            -   name: 💞 Checkout repository 💞
                uses: actions/checkout@v6

            -   name: 💞 Install rarestcheck tool 💞
                uses: rarestype/r2-install-action@v1
                with:
                    archive: rarestcheck.tar.gz

            -   name: 💞 Synchronize templates 💞
                run: rarestcheck sync Templates/Repositories -t autosync --push
                env:
                    AUTOMATION_APP_CLIENT: ${{ vars.AUTOMATION_APP_CLIENT }}
                    AUTOMATION_APP_SECRET: ${{ secrets.AUTOMATION_APP_SECRET }}
                    AUTOMATION_APP_KEY: ${{ secrets.AUTOMATION_APP_KEY }}

            -   name: 💞 Update badge 💞
                uses: rarestype/rarestbadge@v1
                if: always()
                with:
                    badge: Sync
                    title: sync
