name: sync

on:
    workflow_dispatch:
    push:
        branches: [ master ]

jobs:
    push:
        runs-on: ubuntu-latest
        name: push templates

        steps:
            -   name: 💞 Checkout repository 💞
                uses: actions/checkout@v6

            -   name: 💞 Setup credentials 💞
                run: gh auth setup-git
                env:
                    GH_TOKEN: ${{ secrets.AUTOMATION_PAT }}

            -   name: 💞 Synchronize templates 💞
                run: Scripts/SyncAll
                env:
                    GH_TOKEN: ${{ secrets.AUTOMATION_PAT }}
